### PR TITLE
provide custom grafana.ini for anonymous access in sensu-go vagrant

### PR DESCRIPTION
**Pull request by cwjohnston**

### CODE REVIEW

**Comment by hillaryfraley** [comment]
@cwjohnston I'm not sure if this is a problem due to this PR or something else.

When I get to lesson 3, my output isn't matching what's shown in the lesson steps. Here's what I get in terminal:
```
[sensu_go_sandbox]$ sudo systemctl restart sensu-agent
[sensu_go_sandbox]$ sudo yum install -y nginx && sudo systemctl start nginx
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: repos-va.psychz.net
 * extras: centos.mirrors.tds.net
 * updates: ftp.usf.edu
sensu_stable/x86_64/signature                            |  833 B     00:00     
sensu_stable/x86_64/signature                            | 1.0 kB     00:00 !!! 
sensu_stable-source/signature                            |  819 B     00:00     
sensu_stable-source/signature                            |  951 B     00:00 !!! 
No package nginx available.
Error: Nothing to do
[sensu_go_sandbox]$ curl -I http://localhost:80
curl: (7) Failed connect to localhost:80; Connection refused
```

Up to this point, everything works exactly as shown in the lessons. Maybe I'm doing something incorrectly?

**Comment by cwjohnston** [comment]
@hillaryfraley I believe this is unrelated to this PR. I think these two lines indicate the immediate problem:

> No package nginx available.
> Error: Nothing to do

For some reason the `nginx` package is not available in the VM's currently configured package repositories, and therefore the nginx service isn't available to answer the request sent by curl.

**Comment by cwjohnston** [comment]
@hillaryfraley what do you see when you run `cat /etc/redhat-release` ? 

On my side I see `CentOS Linux release 7.5.1804 (Core)`. I can see that the Vagrantfile uses `bento/centos7` as the base image, so I'm guessing you might have a newer CentOS (e.g. 7.7) which would potentially explain what you're seeing.

**Comment by cwjohnston** [comment]
@rgeniesse reports the same here https://github.com/sensu/sensu-docs/pull/1833#discussion_r336302090 on Centos 7.4

**Comment by hillaryfraley** [comment]
@cwjohnston I see:
`CentOS Linux release 7.6.1810 (Core)`

**Pull request merged**
